from __future__ import annotations

from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
import re
import subprocess
import sys

VARIABLE_PATTERN = re.compile(r"{{\s(?P<name>[a-z]+\.[a-z]+)\s}}")
AUTO_GENERATED_HEADER = """<!---
This file is auto-generated by a git hook. Please modify {template_name} if you don't want to lose your work.
-->
"""

GitRunner = Callable[[Sequence[str], Path], str]


@dataclass(frozen=True)
class Arguments:
    input_path: Path
    output_path: Path
    verbose: bool = False


def print_verbose(message: str, verbose: bool) -> None:
    if verbose:
        print(message)


def parse_args(argv: Sequence[str]) -> Arguments | None:
    if len(argv) < 3:
        return None

    return Arguments(
        input_path=Path(argv[1]).resolve(),
        output_path=Path(argv[2]).resolve(),
        verbose=len(argv) == 4 and argv[3] == "-v",
    )


def help_message(script_name: str) -> str:
    return f"{Path(script_name).name} [INPUTFILE] [OUTPUTFILE] [-v]"


def find_git_variables(template_text: str) -> list[str]:
    seen: set[str] = set()
    ordered_variables: list[str] = []

    for match in VARIABLE_PATTERN.finditer(template_text):
        variable_name = match.group("name")
        if variable_name not in seen:
            seen.add(variable_name)
            ordered_variables.append(variable_name)

    return ordered_variables


def repository_name(remote_url: str) -> str:
    stripped_url = remote_url.rstrip("/")
    match = re.search(r"[:/]([^/:]+/[^/]+?)(?:\.git)?$", stripped_url)
    if match is not None:
        return match.group(1)

    repository = stripped_url.rsplit("/", maxsplit=1)[-1].rsplit(":", maxsplit=1)[-1]
    return repository[:-4] if repository.endswith(".git") else repository


def run_git_command(args: Sequence[str], cwd: Path) -> str:
    completed = subprocess.run(
        ["git", *args],
        check=True,
        cwd=cwd,
        capture_output=True,
        text=True,
    )
    return completed.stdout.strip()


def build_git_variables(
    template_text: str,
    cwd: Path,
    runner: GitRunner = run_git_command,
) -> dict[str, str]:
    variable_names = find_git_variables(template_text)
    if not variable_names:
        return {}

    values: dict[str, str] = {
        "remote.origin.url": runner(["config", "--get", "remote.origin.url"], cwd),
        "current.branch": runner(["rev-parse", "--abbrev-ref", "HEAD"], cwd),
        "current.commit": runner(["rev-parse", "HEAD"], cwd),
        "tags": runner(["tag", "--list"], cwd),
    }
    values["repository.name"] = repository_name(values["remote.origin.url"])

    for variable_name in variable_names:
        if variable_name not in values:
            values[variable_name] = runner(["config", variable_name], cwd)

    return values


def render_template(template_text: str, variables: Mapping[str, str]) -> str:
    def replace_match(match: re.Match[str]) -> str:
        variable_name = match.group("name")
        return variables.get(variable_name, match.group(0))

    return VARIABLE_PATTERN.sub(replace_match, template_text)


def stage_output_file(output_path: Path, cwd: Path, runner: GitRunner = run_git_command) -> None:
    try:
        output_argument = str(output_path.resolve().relative_to(cwd.resolve()))
    except ValueError:
        output_argument = str(output_path.resolve())

    runner(["add", output_argument], cwd)


def generate_file(
    arguments: Arguments,
    cwd: Path | None = None,
    runner: GitRunner = run_git_command,
) -> None:
    repo_root = cwd or arguments.input_path.parent
    template_text = arguments.input_path.read_text(encoding="utf-8")

    print_verbose(f"Scanning {arguments.input_path} for git variables.", arguments.verbose)
    variables = build_git_variables(template_text, repo_root, runner)
    rendered_text = render_template(template_text, variables)
    output_contents = AUTO_GENERATED_HEADER.format(
        template_name=arguments.input_path.name,
    ) + rendered_text

    arguments.output_path.write_text(output_contents, encoding="utf-8")
    stage_output_file(arguments.output_path, repo_root, runner)
    print_verbose(f"Updated {arguments.output_path}.", arguments.verbose)


def main(argv: Sequence[str] | None = None) -> int:
    actual_argv = list(sys.argv if argv is None else argv)
    arguments = parse_args(actual_argv)
    if arguments is None:
        print(help_message(actual_argv[0] if actual_argv else "replace_by_git_vars.py"))
        return 1

    generate_file(arguments)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
