name: Makefile Linter

on:
  push:
    branches:
      - main
    paths:
      - "**Makefile**"
  workflow_dispatch:
  pull_request:

permissions: {}

jobs:
  checkmake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v3

      - name: Run checkmate
        id: checkmake
        uses: Uno-Takashi/checkmake-action@main
