name: Lua linter

on:
  push:
    branches:
      - main
      - dev
      - "codex/**"
    paths:
      - '**.lua'
  workflow_dispatch:
  pull_request:

permissions: {}

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Lua
        uses: leafo/gh-actions-lua@v10

      - name: Setup LuaRocks
        uses: leafo/gh-actions-luarocks@v5

      - name: Install luacheck
        run: luarocks install luacheck

      - name: Run Lua Linter
        run: luacheck config/nvim
