name: Shell script linter

on:
  push:
    branches:
      - main
    paths:
      - '**.sh'
  workflow_dispatch:
  pull_request:

permissions: {}

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run ShellCheck
        id: shellcheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -e SC2086 -e SC2148 -e SC2296 -e SC1090 -e SC2034 -e SC1091 -e SC2046
